spin_manifest_version = 2

[application]
name = "frontend"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "app", destination = "/" }]
