spin_manifest_version = 2

[application]
name = "foo"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "bar"

[component.bar]
source = "target/wasm32-wasi/release/bar.wasm"
allowed_outbound_hosts = ["https://*:443"]
files = [{ source = "./", destination = "/" }]
[component.bar.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "bar"
watch = ["src/**/*.rs", "Cargo.toml"]


[[trigger.http]]
route = "/upload/..."
component = "static"

[component.static]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "assets", destination = "/" }]
