spin_manifest_version = 2

[application]
name = "foo"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[variables]
arg_foo = { required = true }
arg2 = { required = true, secret = true }
arg3 = { required = true }
arg4 = { required = true }
arg5 = { required = true, secret = true }
arg6 = { required = true, secret = true }

[[trigger.http]]
route = "/..."
component = "bar"

[component.bar]
source = "target/wasm32-wasi/release/bar.wasm"
allowed_outbound_hosts = []
[component.bar.variables]
arg_foo = "{{ arg_foo }}"
arg2 = "{{ arg2 }}"
arg3 = "{{ arg3 }}"
arg4 = "{{ arg4 }}"
arg5 = "{{ arg5 }}"
arg6 = "{{ arg6 }}"

[component.bar.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "bar"
watch = ["src/**/*.rs", "Cargo.toml"]
