package seungjin:rock@0.1.0;

world rock {
    export calc;
}

/// An example world for the component to target.
interface calc {
    add: func(x: s32, y: s32) -> s32;
    sub: func(x: s32, y: s32) -> s32;
}